language: rust

rust:
  - stable

cache: cargo

before_cache: cargo install cargo-tarpaulin

script:
  - cargo test --verbose --all

after_success:
  - CARGO_MANIFEST_DIR=`pwd` cargo tarpaulin --out Xml
  - bash <(curl -s https://codecov.io/bash)
  
